#!/usr/bin/env bash

rm -f /tmp/fx-profile/places.sqlite

/usr/local/bin/docker run \
  -e DISPLAY=host.docker.internal:0 \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v /tmp/fx-profile:/home/user/.mozilla/firefox/default-release \
  --rm firefox-ephemeral \
  -profile /home/user/.mozilla/firefox/default-release \
  "https://www.whatsmybrowser.org/"