#!/usr/bin/env bash

xhost +local:docker

docker run \
  --rm \
  --entrypoint firefox \
  -e DISPLAY="$DISPLAY" \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v /tmp/fx-profile:/home/user/.mozilla/firefox/default-release \
  firefox-ephemeral \
  -profile /home/user/.mozilla/firefox/default-release \
  -private-window \
  "https://www.whatsmybrowser.org/"