#!/usr/bin/env bash

# Lista de paquetes a instalar
paquetes=("acpi" "upower")

# Función para verificar si un paquete está instalado (Debian/Ubuntu/Kali)
paquete_instalado_apt() {
    dpkg -l "$1" | grep -q '^ii'  
}

# Función para verificar si un paquete está instalado (CentOS/RHEL)
paquete_instalado_yum() {
    yum list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Fedora)
paquete_instalado_dnf() {
    dnf list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Arch Linux)
paquete_instalado_pacman() {
    pacman -Qi "$1" &> /dev/null
}

# Detectar el sistema operativo
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
fi

# Instalar paquetes basados en el sistema operativo
for paquete in "${paquetes[@]}"; do
    case $OS in
        "debian"|"ubuntu"|"kali")
            if ! paquete_instalado_apt "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo apt-get install -y "$paquete"
            fi
            ;;
        "centos"|"rhel")
            if ! paquete_instalado_yum "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo yum install -y "$paquete"
            fi
            ;;
        "fedora")
            if ! paquete_instalado_dnf "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo dnf install -y "$paquete"
            fi
            ;;
        "arch")
            if ! paquete_instalado_pacman "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo pacman -S --noconfirm "$paquete"
            fi
            ;;
        *)
            ;;
    esac
done


#se ejecuta dos comando en este script
#upower -i /org/freedesktop/UPower/devices/battery_BAT0
#acpi -b

# Ejecuta el comando y guarda la salida en una variable
battery_info=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0)

# Extrae los datos relevantes de la batería
#battery_status=$(echo $battery_info | grep -oP 'state:\s+\K\w+')
energy_rate=$(echo $battery_info | grep -oP 'energy-rate:\s+\K[\d.]+')
time_to_full=$(echo $battery_info | grep -oP 'time to full:\s+\K[\d.]+')
#percentage=$(echo $battery_info | grep -oP 'percentage:\s+\K[\d.]+')


# Imprime los resultados
#echo "Estado de la batería: $battery_status"
echo "Consumo de energía: $energy_rate W"
echo "Tiempo estimado para carga completa: $time_to_full minutos"
echo "adaptador corriente conectado"
acpi -a #adaptador de corriente
#echo "Porcentaje de batería: $percentage%"
acpi -b
