#!/bin/bash

echo ""
echo "enviar"
echo "scp -P Port local_file IP-remote_machine:~"
echo ""
echo "recibir"
echo "scp -P Port IP-remote_machine:~/remote_file ."

echo -e "\n\033[1;33m_________________________________________________________\033[0m\n"

if [[ $# -eq 0 ]]; then
    echo "Uso: $0 <archivo>"
    exit 1
fi

#echo "Buscando archivo de configuración SSH..."
CONFIG_FILE="$HOME/.ssh/config"
if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "El archivo de configuración SSH no existe."
    exit 1
fi
echo ""

#echo "Procesando archivo de configuración SSH..."
declare -A host_user_map
declare -A host_ip_map
declare -A host_port_map
current_host=""

while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ $line =~ ^Host\ +([^*]+)$ ]]; then
        current_host=${BASH_REMATCH[1]}
    elif [[ $current_host != "" ]]; then
        if [[ $line =~ ^\ +User\ +(.+)$ ]]; then
            host_user_map["$current_host"]=${BASH_REMATCH[1]}
        elif [[ $line =~ ^\ +HostName\ +(.+)$ ]]; then
            host_ip_map["$current_host"]=${BASH_REMATCH[1]}
        elif [[ $line =~ ^\ +Port\ +(.+)$ ]]; then
            host_port_map["$current_host"]=${BASH_REMATCH[1]}
        fi
    fi
done < "$CONFIG_FILE"
echo ""

if [ ${#host_user_map[@]} -eq 0 ]; then
    echo "No se encontraron hosts en el archivo de configuración."
    exit 1
fi

echo "Seleccione un host para la operación:"
echo ""
select host_choice in "${!host_user_map[@]}"; do
    if [[ -n "$host_choice" ]]; then
        user=${host_user_map["$host_choice"]}
        ip=${host_ip_map["$host_choice"]}
        port=${host_port_map["$host_choice"]:-22} # Default to port 22 if not specified
        break
    else
        echo "Selección no válida. Intente de nuevo."
    fi
done

remote_machine="${user}@${ip}"
echo ""
echo "Ha seleccionado: $remote_machine con puerto $port"
echo ""
echo -e "\n\033[1;34m_________________________________________________________\033[0m\n"
echo ""
echo "¿Enviar o recibir un archivo? (escriba 'e' o 'r')"
read option
echo ""

scp_command=""
if [[ $option == "e" ]]; then
    local_file=$1
    scp_command="scp -P $port $local_file $remote_machine:~"
elif [[ $option == "r" ]]; then
    remote_file=$1
    scp_command="scp -P $port $remote_machine:~/$remote_file ."
else
    echo "Opción no válida. Por favor, elija 'e' o 'r'."
    exit 1
fi

echo "El comando a ejecutar es:"
echo ""
echo "$scp_command"
$scp_command

echo ""
echo -e "\n\033[1;34m_________________________________________________________\033[0m\n"




