#!/bin/bash

# Check if the user@IP argument was provided
if [ -z "$1" ]; then
    echo "Error: You must provide the user@IP argument"
    exit 1
fi

# Check if the ssh_port argument was provided
if [ -z "$2" ]; then
    echo "Error: You must provide the ssh_port argument"
    exit 1
fi

# Get the user@IP from the argument
client="$1"

# Get the SSH port from the second argument
ssh_port="$2"

echo -e "\n\033[1;37m_________________________________________________________\033[0m\n"
# Display the command that will be executed
echo ""
echo -e "\033[1;32mThe command this script executes is to copy is:\033[0m"
echo ""
echo -e "\033[1;33mssh-copy-id -i ~/.ssh/id_ed25519.pub -p $ssh_port $client\033[0m"
echo ""

echo -e "\n\033[1;37m_________________________________________________________\033[0m\n"

# Generate the new SSH key
echo -e "\033[1;32mTo generate the ssh-keygen: \033[0m"
echo -e "\033[1;32mssh-keygen -t ed25519 -f ~/.ssh/id_ed25519\033[0m"
echo ""
ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519

echo -e "\n\033[1;37m_________________________________________________________\033[0m\n"
# Add a space before the next command execution
echo ""

# Copy the SSH key to the host
echo -e "\033[1;32mExecuting: \033[0m"
echo -e "\033[1;32mssh-copy-id -i ~/.ssh/id_ed25519.pub -p $ssh_port $client\033[0m"
echo ""
ssh-copy-id -i ~/.ssh/id_ed25519.pub -p "$ssh_port" "$client"

echo -e "\n\033[1;37m_________________________________________________________\033[0m\n"
# Final message
echo ""
echo -e "\033[1;34mKey successfully copied to $client on port $ssh_port\033[0m"
