#!/bin/bash

detener_y_eliminar_contenedor() {
    IMAGE_NAME="${TAR_FILE%.tar}"
    CONTAINER_NAME="${IMAGE_NAME}_container"

    if [ "$(sudo docker ps -a -q -f name=$CONTAINER_NAME -f status=exited)" ]; then
        sudo docker rm $CONTAINER_NAME > /dev/null
    fi

    if [ "$(sudo docker ps -q -f name=$CONTAINER_NAME)" ]; then
        sudo docker stop $CONTAINER_NAME > /dev/null
        sudo docker rm $CONTAINER_NAME > /dev/null
    fi

    if [ "$(sudo docker images -q $IMAGE_NAME)" ]; then
        sudo docker rmi $IMAGE_NAME > /dev/null
    fi
}

trap ctrl_c INT

function ctrl_c() {
    echo -e "\e[1mEliminando el laboratorio, por favor espera un momento...\e[0m"
    detener_y_eliminar_contenedor
    echo -e "\nEl laboratorio ha sido completamente eliminado del sistema."
    exit 0
}

if [ $# -ne 1 ]; then
    echo "Uso: $0 <archivo_tar>"
    exit 1
fi

if ! command -v docker &> /dev/null; then
    echo -e "\033[1;36m\nDocker no está instalado. Instalando Docker...\033[0m"
    sudo apt update
    sudo apt install docker.io -y
    echo -e "\033[1;36m\nHabilitando el servicio de Docker. Por favor espera un momento...\033[0m"
    sleep 10
    sudo systemctl restart docker && sudo systemctl enable docker
    if [ $? -eq 0 ]; then
        echo "Docker ha sido instalado exitosamente."
    else
        echo "Error al instalar Docker. Por favor, verifica e intenta nuevamente."
        exit 1
    fi
fi

TAR_FILE="$1"

echo -e "\e[1;93m\nDesplegando la máquina vulnerable, por favor espera un momento.\e[0m"
detener_y_eliminar_contenedor
sudo docker load -i "$TAR_FILE" > /dev/null

if [ $? -eq 0 ]; then
    IMAGE_NAME=$(basename "$TAR_FILE" .tar)
    CONTAINER_NAME="${IMAGE_NAME}_container"

    sudo docker run -d --name $CONTAINER_NAME $IMAGE_NAME > /dev/null

    IP_ADDRESS=$(sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_NAME)

    echo -e "\e[1;96m\nMáquina desplegada, su dirección IP es --> \e[0m\e[1;97m$IP_ADDRESS\e[0m"

    echo -e "\e[1;91m\nPresiona Ctrl+C cuando hayas terminado con la máquina para eliminarla\e[0m"

else
    echo -e "\e[91m\nOcurrió un error al cargar el laboratorio en Docker.\e[0m"
    exit 1
fi

while true; do
    sleep 1
done
