#!/usr/bin/env bash

# Función para verificar si un paquete está instalado
paquetes=("docker.io" "distrobox")

# Función para verificar si un paquete está instalado (Debian/Ubuntu/Kali)
paquete_instalado_apt() {
    dpkg -l "$1" | grep -q '^ii'
}

# Función para verificar si un paquete está instalado (CentOS/RHEL)
paquete_instalado_yum() {
    yum list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Fedora)
paquete_instalado_dnf() {
    dnf list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Arch Linux)
paquete_instalado_pacman() {
    pacman -Qi "$1" &> /dev/null
}

# Detectar el sistema operativo
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
fi

# Instalar paquetes basados en el sistema operativo
for paquete in "${paquetes[@]}"; do
    case $OS in
        "debian"|"ubuntu"|"kali")
            if ! paquete_instalado_apt "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo apt-get install -y "$paquete"
            fi
            ;;
        "centos"|"rhel")
            if ! paquete_instalado_yum "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo yum install -y "$paquete"
            fi
            ;;
        "fedora")
            if ! paquete_instalado_dnf "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo dnf install -y "$paquete"
            fi
            ;;
        "arch")
            if ! paquete_instalado_pacman "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo pacman -S --noconfirm "$paquete"
            fi
            ;;
        *)
            ;;
    esac
done

# Crear el grupo docker y añadir el usuario actual al grupo
if ! getent group docker > /dev/null 2>&1; then
    sudo groupadd docker
fi

sudo usermod -aG docker "$USER"

# Pregunta al usuario si quiere arreglar los permisos
read -p "¿Quieres arreglar los permisos? (s/enter continuar): " respuesta

if [[ $respuesta == "s" || $respuesta == "S" ]]; then
    echo "Arreglando permisos..."
    newgrp docker
    ls -l /var/run/docker.sock
    sudo chown root:docker /var/run/docker.sock
    sudo systemctl restart docker
    echo "Permisos arreglados."
else
    echo "No se han realizado cambios."
fi

# Opciones de distribuciones
echo "Elige una distribución para instalar con DistroBox:"
echo "1) Debian Toolbox 13"
echo "2) Fedora Toolbox 42"
echo "3) Fedora Toolbox Rawhide"
echo "4) RHEL/UBI9 Toolbox"
echo "5) Ubuntu Toolbox 24.04"
echo "6) Ubuntu Toolbox (latest)"
echo "7) Kali Linux"
echo "8) ArchLinux"
echo "9) Mas Distros"

# Leer la elección del usuario
read -p "Introduce el número de tu elección: " choice

# Asignar la imagen correspondiente a la elección
case $choice in
    1) image="quay.io/toolbx-images/debian-toolbox:13" ;;
    2) image="quay.io/fedora/fedora-toolbox:42" ;;
    3) image="quay.io/fedora/fedora-toolbox:rawhide" ;;
    4) image="registry.access.redhat.com/ubi9/toolbox" ;;
    5) image="toolbox:24.04" ;;
    6) image="quay.io/toolbx/ubuntu-toolbox:latest" ;;
    7) image="docker.io/kalilinux/kali-rolling:latest" ;;
    8) image="docker.io/library/archlinux:latest" ;;
    9)
        echo "Visita: https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#containers-distros"
        exit 0
        ;;
    *)
        echo "Opción no válida."
        exit 1
        ;;
esac

# Crear la distrobox
distrobox create -i "$image"