#!/bin/bash

echo ""

# Verificar si el archivo /etc/resolv.conf existe
if [ -f /etc/resolv.conf ]; then
    echo -e "\033[1;33mConfigured DNS servers:\033[0m"
    
    # Extraer y mostrar las líneas no comentadas que contienen "nameserver"
    grep -v '^\s*#' /etc/resolv.conf | grep "nameserver" | awk '{print "\033[1;31m" $2 "\033[0m"}'
else
    echo -e "\033[1;33mThe /etc/resolv.conf file does not exist.\033[0m"
fi

echo ""