#!/usr/bin/env bash


wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg


sudo apt-get install apt-transport-https
sudo apt-get update && sudo apt-get install elasticsearch



# Importa la llave y repositorio
curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" \
  | sudo tee /etc/apt/sources.list.d/elastic-8.x.list

# Instala
sudo apt update
sudo apt install filebeat elasticsearch -y



# copia a /etc/ssl/certs/ con permisos abiertos
sudo cp /etc/elasticsearch/certs/http_ca.crt /etc/ssl/certs/es-http-ca.crt
sudo chmod 644 /etc/ssl/certs/es-http-ca.crt
