#!/bin/bash

echo ""

# Function to display help message and ask if the user wants to continue
show_help_and_confirm() {
    echo
    echo "The command this script executes is:"
    echo ""
    echo "1) - sudo nmap 10.10.10.3 -p- --open -sS --min-rate 5000 -v -n -oG allPorts "
    echo "2) - sudo nmap 10.10.10.3 -p- --open -sS --min-rate 5000 -v -n -Pn -oG allPorts"
    echo
    read -n1 -p "Press Enter to continue or 'c' to exit. " response

    echo "" # Add space after input
    echo "_________________________________________________________"
    echo ""

    # Convert response to lowercase and check if 'c' was pressed
    response=$(echo "$response" | tr '[:upper:]' '[:lower:]')
    if [ "$response" == "c" ]; then
        echo "Exiting the script."
        exit 0
    fi
}

# Check if -h argument is passed
if [ "$1" == "-h" ]; then
    show_help_and_confirm
fi

# Check if IP was passed as an argument
if [ -z "$1" ]; then
    echo "You must specify the IP as a script argument."
    exit 1
fi

echo ""
echo "Select the type of scan you want to use:"
echo ""
echo "1. Run scan without Pn "
echo "2. Run scan with Pn "
echo ""
echo "_________________________________________________________"
echo "" # Add space after input

echo "The command to execute is:         sudo nmap "$1" -p- --open -sS --min-rate 5000 -v -n -oG allPorts "
read -n1 -p "Choose (1 or 2): " choice

echo "" # Add space after input
echo "_________________________________________________________"
echo ""

case $choice in
    1)
        echo "Running scan without Pn..."
        #nmap -p- --open -T5 -v -n "$1" -oG allPorts
        sudo nmap "$1" -p- --open -sS --min-rate 5000 -v -n -oG allPorts
        ;;
    2)
        echo "Running scan with Pn..."
        #nmap -p- --open -T5 -v -n -Pn "$1" -oG allPorts
        sudo nmap "$1" -p- --open -sS --min-rate 5000 -v -n -Pn -oG allPorts
        ;;
    *)
        echo "Invalid option. Please choose 1 or 2."
        ;;
esac
