#!/usr/bin/env bash

# Función para verificar si un paquete está instalado
paquete_instalado() {
    dpkg -l "$1" | grep -q '^ii'
}

# Verificar si iptables está en el PATH
if command -v iptables &>/dev/null; then
    echo "iptables está disponible en el PATH."
else
    echo "iptables no se encontró en el PATH."
fi

# Verificar si iptables está instalado
if paquete_instalado "iptables"; then
    echo "El paquete iptables ya está instalado."
else
    echo "Instalando el paquete iptables..."
    sudo apt-get install -y iptables
fi

paquetes=("rsyslog" "fail2ban")

for paquete in "${paquetes[@]}"; do
    if paquete_instalado "$paquete"; then
        echo "El paquete $paquete ya está instalado."
    else
        echo "Instalando el paquete $paquete..."
        sudo apt-get install -y "$paquete"
    fi
done

sleep 1

sudo cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local

JAIL_FILE="/etc/fail2ban/jail.local"

if [[ -f "$JAIL_FILE" ]]; then
    sudo cp "$JAIL_FILE" "${JAIL_FILE}.bak"
    sudo sed -i '/^\[sshd\]/,/^backend = %\(sshd_backend\)s/s/^/#/' "$JAIL_FILE"
    sudo sed -i '1 i\[sshd]\nenabled = true\nport = ssh\nfilter = sshd\nlogpath = /var/log/auth.log\nmaxretry = 2\n' "$JAIL_FILE"
    echo "Modificaciones aplicadas con éxito."
else
    echo "El archivo $JAIL_FILE no existe."
fi

sleep 1

# Aliases para .bashrc
echo "alias rs2='sudo nano /etc/rsyslog.conf'" >> ~/.bashrc
echo "alias f2mod='sudo nano /etc/fail2ban/jail.local'" >> ~/.bashrc
echo "alias f2r='sudo systemctl restart fail2ban'" >> ~/.bashrc
echo "alias f2s='sudo systemctl status fail2ban'" >> ~/.bashrc
echo "alias f2b='read -p \"Ingresa IP a banear: \" ip && sudo fail2ban-client set sshd banip \$ip'" >> ~/.bashrc
echo "alias f2u='read -p \"Ingresa IP a unban: \" ip && sudo fail2ban-client set sshd unbanip \$ip'" >> ~/.bashrc
echo "alias f2j='sudo fail2ban-client status sshd'" >> ~/.bashrc

# Aliases para .zshrc
echo "alias rs2='sudo nano /etc/rsyslog.conf'" >> ~/.zshrc
echo "alias f2mod='sudo nano /etc/fail2ban/jail.local'" >> ~/.zshrc
echo "alias f2r='sudo systemctl restart fail2ban'" >> ~/.zshrc
echo "alias f2s='sudo systemctl status fail2ban'" >> ~/.zshrc
echo "alias f2b='read -p \"Ingresa IP a banear: \" ip && sudo fail2ban-client set sshd banip \$ip'" >> ~/.zshrc
echo "alias f2u='read -p \"Ingresa IP a unban: \" ip && sudo fail2ban-client set sshd unbanip \$ip'" >> ~/.zshrc
echo "alias f2j='sudo fail2ban-client status sshd'" >> ~/.zshrc

sudo systemctl enable --now fail2ban

f2bcomm

echo ""
echo "IMPORTANTE"
echo ""
echo "no se te olvide cambiar los tiempos de jail con f2mod alias"
echo "para tiempo ilimitado: bantime = -1"
echo "para ver los comandos de nuevo f2bcomm"
echo "agrega a f2mod estas lineas para whitelist"
echo '''[DEFAULT]
ignoreip = 127.0.0.1/8 192.168.0.1'''
