#!/bin/bash



#para que no pida confirmacion
rm -f ~/Downloads/.vpnitos/*


# Lista de paquetes a instalar
paquetes=("openvpn" "dialog" "tmux")

# Función para verificar si un paquete está instalado (Debian/Ubuntu/Kali)
paquete_instalado_apt() {
    dpkg -l "$1" | grep -q '^ii'  
}

# Función para verificar si un paquete está instalado (CentOS/RHEL)
paquete_instalado_yum() {
    yum list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Fedora)
paquete_instalado_dnf() {
    dnf list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Arch Linux)
paquete_instalado_pacman() {
    pacman -Qi "$1" &> /dev/null
}

# Detectar el sistema operativo
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
fi

# Instalar paquetes basados en el sistema operativo
for paquete in "${paquetes[@]}"; do
    case $OS in
        "debian"|"ubuntu"|"kali")
            if ! paquete_instalado_apt "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo apt-get install -y "$paquete"
            fi
            ;;
        "centos"|"rhel")
            if ! paquete_instalado_yum "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo yum install -y "$paquete"
            fi
            ;;
        "fedora")
            if ! paquete_instalado_dnf "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo dnf install -y "$paquete"
            fi
            ;;
        "arch")
            if ! paquete_instalado_pacman "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo pacman -S --noconfirm "$paquete"
            fi
            ;;
        *)
            ;;
    esac
done





function mktem() {
    new_dir=$(mktemp -d)
    echo "Directorio creado en: $new_dir"
    cd "$new_dir" || return
    echo "Cambiado al directorio: $PWD"
}

mktem




# Crear el directorio ~/Downloads/.vpnitos si no existe
mkdir -p ~/Downloads/.vpnitos


git clone --depth 1 https://github.com/4rji/4rji.git
cd 4rji
unzip Ban1_aa12.zip  



# Navegar al directorio Ban1_aa12
cd Ban1_aa12



# Mover todos los archivos al directorio ~/Downloads/.vpnitos
cp * ~/Downloads/.vpnitos/


# Cambiar la contraseña (asumiendo que "cc.txt" contiene la nueva contraseña)
echo "Reemplazar contraseña cc"
sudo mv ~/Downloads/.vpnitos/cc.txt /


