#!/bin/bash

mensaje="a este script agregale  espacios para que se vea mas limpio como este ejemplo:
echo 
echo _________________________________________________________
echo 


y también modifica las preguntas para que no esperen por enter, como este ejemplo:
read -n1 -p ¿Ejemplo pregunta? [S/n] 

no modifiques nada del script, solo agrega espacios:"







echo -n "$mensaje" | xclip -selection clipboard



echo "Copiado al portapapeles."




#agregale  espacios para que se vea mas limpio como este ejemplo:
#echo ""
#echo "_________________________________________________________"
#echo ""

#y también modifica las preguntas para que no esperen por enter, como este ejemplo:
#read -n1 -p ¿Ejemplo pregunta? [S/n] 

#y agrega al menos 3 colores o mas para que se vea bien las lineas y preguntas