#!/usr/bin/env bash




set -e

# Lista de paquetes a instalar
paquetes=("docker-compose" "docker.io")

# Función para verificar si un paquete está instalado (Debian/Ubuntu/Kali)
paquete_instalado_apt() {
    dpkg -l "$1" | grep -q '^ii'  
}

# Función para verificar si un paquete está instalado (CentOS/RHEL)
paquete_instalado_yum() {
    yum list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Fedora)
paquete_instalado_dnf() {
    dnf list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Arch Linux)
paquete_instalado_pacman() {
    pacman -Qi "$1" &> /dev/null
}

# Detectar el sistema operativo
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
fi

# Instalar paquetes basados en el sistema operativo
for paquete in "${paquetes[@]}"; do
    case $OS in
        "debian"|"ubuntu"|"kali")
            if ! paquete_instalado_apt "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo apt-get install -y "$paquete"
            fi
            ;;
        "centos"|"rhel")
            if ! paquete_instalado_yum "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo yum install -y "$paquete"
            fi
            ;;
        "fedora")
            if ! paquete_instalado_dnf "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo dnf install -y "$paquete"
            fi
            ;;
        "arch")
            if ! paquete_instalado_pacman "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo pacman -S --noconfirm "$paquete"
            fi
            ;;
        *)
            ;;
    esac
done






URL="https://raw.githubusercontent.com/4rji/dotfiles/refs/heads/main/dockerfiles/dockerfile-mini-debian"
      

IMAGE="firefox-rdp"
CONTAINER="firefox-rdp"

# bajar Dockerfile
curl -fsSL "$URL" -o Dockerfile

# build imagen
docker build -t "$IMAGE" .

# run en background
docker run -d --rm --name "$CONTAINER" -p 3389:3389 "$IMAGE"

echo ""
echo "✅ Imagen y contenedor listos"
echo ""
echo "Usar el script: fx11"
echo "  -s  start  → encender remotamente el contenedor"
echo "  -o  stop   → apagar remotamente el contenedor"
echo ""
