#!/usr/bin/env bash


# Generar archivos de 10, 20, 30 y 40 MB respectivamente
dd if=/dev/urandom of=file_10MB bs=1M count=10 2>/dev/null
dd if=/dev/urandom of=file_20MB bs=1M count=20 2>/dev/null
dd if=/dev/urandom of=file_30MB bs=1M count=30 2>/dev/null
dd if=/dev/urandom of=file_40MB bs=1M count=40 2>/dev/null

# Mostrar mensaje de finalización
echo "4 files created"
