#!/bin/bash

# Función para preguntar al usuario si desea continuar
function continuar_siguiente {
    echo -n -e "\n¿Desea continuar con el siguiente comando? [S/n]: "
    read -n 1 continuar
    if [[ $continuar == "n" || $continuar == "N" ]]; then
        exit
    fi
}

# Buscar archivos con el bit setuid activado
echo -e "\e[1;34mArchivos con el bit setuid activado:\e[0m"
echo "_______________________________________"
echo "find / -perm -u=s -type f 2>/dev/null"
find / -perm -u=s -type f 2>/dev/null
continuar_siguiente

# Separador
echo -e "\n\e[32m_______________________________________\e[0m\n"

# Buscar archivos con el bit setgid activado
echo -e "\e[1;34mArchivos con el bit setgid activado:\e[0m"
echo "_______________________________________"
echo "find / -perm -g=s -type f 2>/dev/null"
find / -perm -g=s -type f 2>/dev/null
continuar_siguiente

# Separador
echo -e "\n\e[32m_______________________________________\e[0m\n"

# Mostrar las capacidades de Linux
echo -e "\e[1;34mCapacidades de Linux:\e[0m"
echo "_______________________________________"
echo "getcap -r / 2>/dev/null"
getcap -r / 2>/dev/null

