#!/usr/bin/python3

print("to receive files with Python 2, from the other machine, do a curl like this:")
print("curl -T secrec http://192.168.88.19:8000")
print("")


from http.server import SimpleHTTPRequestHandler, HTTPServer

class SputHTTPRequestHandler(SimpleHTTPRequestHandler):
    def do_PUT(self):
        print(self.headers)
        length = int(self.headers['Content-Length'])
        path = self.translate_path(self.path)
        with open(path, 'wb') as dst:
            dst.write(self.rfile.read(length))

if __name__ == '__main__':
    HTTPServer(('', 8000), SputHTTPRequestHandler).serve_forever()

