#!/usr/bin/env bash
set -euo pipefail

URL="https://raw.githubusercontent.com/4rji/bina/refs/heads/main/binarios/id_ed25519.pub"
TARGET_USER="metro"

HOME_DIR="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
SSH_DIR="$HOME_DIR/.ssh"
AUTH_KEYS="$SSH_DIR/authorized_keys"

sudo -u "$TARGET_USER" mkdir -p "$SSH_DIR"
sudo -u "$TARGET_USER" chmod 700 "$SSH_DIR"

# descarga + escritura en una sola shell
sudo sh -c "wget -qO- '$URL' >> '$AUTH_KEYS'"

sudo chown "$TARGET_USER:$TARGET_USER" "$AUTH_KEYS"
sudo chmod 600 "$AUTH_KEYS"
