#!/usr/bin/env bash

# Verificar argumentos
if [ $# -ne 2 ]; then
    echo "Uso: $0 <nombre> <IP>"
    exit 1
fi

# Argumentos
nombre="$1"
ip="$2"

# Directorio base
base_dir="$HOME/4rjinotes/htb"

# Crear estructura si no existe
mkdir -p "$base_dir/$nombre"

# Nombre del archivo markdown
foldername_with_extension="$nombre.md"

# Mostrar información
echo "Definiendo las siguientes variables:"
echo ""
echo "export htf=\"$base_dir/$nombre/$foldername_with_extension\""
echo "export htcon=\"$base_dir/$nombre\""
echo "export ip=\"$ip\""
echo "export maquina=\"$nombre\""

# Comentar variables previas
sed -i 's/^export htf=/##&/' ~/.zshrc
sed -i 's/^export htcon=/##&/' ~/.zshrc
sed -i 's/^export ip=/##&/' ~/.zshrc
sed -i 's/^export maquina=/##&/' ~/.zshrc

# Añadir nuevas variables
{
  echo ""
  echo "# Variables definidas por el script htp"
  echo "export htf=\"$base_dir/$nombre/$foldername_with_extension\""
  echo "export htcon=\"$base_dir/$nombre\""
  echo "export ip=\"$ip\""
  echo "export maquina=\"$nombre\""
} >> ~/.zshrc

echo ""
echo "Variables agregadas a ~/.zshrc"
echo "Reinicia la shell"
echo ""