#!/bin/bash

# Verificar si se proporcionó el nombre de la máquina
if [ -z "$1" ]; then
  echo "Error: No se proporcionó el nombre de la máquina."
  echo "Uso: $0 <nombre_maquina>"
  exit 1
fi

#ejecutar el script target1
target1

iniciar() {
  local base_dir="/home/ass/Documents/GitHub/4rji/4rjinotes/htb"
  local new_dir="$base_dir/$1"
  local template_file="/home/ass/.template.md"
  local machine_name="$1"
  local new_file="$new_dir/$machine_name.md"

  # Crear directorio y copiar plantilla
  mkdir -p "$new_dir" && cd "$new_dir" && mkdir -p nmap content exploits scripts && cp "$template_file" "$machine_name.md"

  # Abrir primera ventana de Kitty en el directorio ra  z
  kitty @ launch zsh -c "cd \"$new_dir\"; exec zsh"

  # Abrir segunda ventana de Kitty en el directorio nmap
  kitty @ launch zsh -c "cd \"$new_dir/nmap\"; exec zsh"

  # Abrir tercera ventana de Kitty en el directorio content
  kitty @ launch zsh -c "cd \"$new_dir/content\"; exec zsh"

  # Mostrar mensaje final
  echo ""
  pwd
}

# Llamar a la función iniciar con el nombre de la máquina como argumento
iniciar "$1"
