#!/usr/bin/env bash

# Ejecutar iodine con los parámetros dados
sudo iodine -P carp -T A mic2.4rji.com tunel.midominio.com &

# Esperar a que iodine establezca la conexión (ajusta si es necesario)
sleep 10

# Verificar conectividad con ping
if ping -c1 172.16.0.1 >/dev/null 2>&1; then
    echo "Conectado al túnel"
else
    echo "Fallo la conexión al túnel"
fi


echo "sudo pkill iodine"
