#!/bin/bash


#!/bin/bash

# Obtener el nombre del usuario actual
USER=$(whoami)

# Verificar si el usuario está en el grupo docker
if groups $USER | grep &>/dev/null '\bdocker\b'; then
    echo "El usuario $USER ya está en el grupo docker."
else
    echo "El usuario $USER no está en el grupo docker. Agregando..."
    sudo usermod -aG docker $USER

    # Pedir al usuario que cierre sesión para aplicar los cambios
    echo "Se ha agregado al grupo docker. Por favor, cierra la sesión y vuelve a iniciarla."
fi



#to avoid environment env instalation
pip3 install Flask --break-system-packages &>/dev/null




# Lista de paquetes a instalar
paquetes=("python3" "zsh" "python3-flask")

# Función para verificar si un paquete está instalado (Debian/Ubuntu/Kali)
paquete_instalado_apt() {
    dpkg -l "$1" | grep -q '^ii'  
}

# Función para verificar si un paquete está instalado (CentOS/RHEL)
paquete_instalado_yum() {
    yum list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Fedora)
paquete_instalado_dnf() {
    dnf list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Arch Linux)
paquete_instalado_pacman() {
    pacman -Qi "$1" &> /dev/null
}

# Detectar el sistema operativo
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
fi

# Instalar paquetes basados en el sistema operativo
for paquete in "${paquetes[@]}"; do
    case $OS in
        "debian"|"ubuntu"|"kali")
            if ! paquete_instalado_apt "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo apt-get install -y "$paquete"
            fi
            ;;
        "centos"|"rhel")
            if ! paquete_instalado_yum "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo yum install -y "$paquete"
            fi
            ;;
        "fedora")
            if ! paquete_instalado_dnf "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo dnf install -y "$paquete"
            fi
            ;;
        "arch")
            if ! paquete_instalado_pacman "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo pacman -S --noconfirm "$paquete"
            fi
            ;;
        *)
            ;;
    esac
done


python3 /opt/4rji/bin/labprogram
