#!/bin/bash

# List of packages to install
packages=("scrub" "coreutils")

# Function to check if a package is installed (Debian/Ubuntu/Kali)
package_installed_apt() {
    dpkg -l "$1" | grep -q '^ii'  
}

# Function to check if a package is installed (CentOS/RHEL)
package_installed_yum() {
    yum list installed "$1" &> /dev/null
}

# Function to check if a package is installed (Fedora)
package_installed_dnf() {
    dnf list installed "$1" &> /dev/null
}

# Function to check if a package is installed (Arch Linux)
package_installed_pacman() {
    pacman -Qi "$1" &> /dev/null
}

# Detect the operating system
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
fi

# Install packages based on the operating system
for package in "${packages[@]}"; do
    case $OS in
        "debian"|"ubuntu"|"kali")
            if ! package_installed_apt "$package"; then
                echo ""
                echo "_________________________________________________________"
                echo ""
                echo -e "\033[31mInstalling package $package...\033[0m"
                echo -e "\033[34msudo apt-get install -y $package\033[0m"
                sudo apt-get install -y "$package"
            fi
            ;;
        "centos"|"rhel")
            if ! package_installed_yum "$package"; then
                echo ""
                echo "_________________________________________________________"
                echo ""
                echo -e "\033[32mInstalling package $package...\033[0m"
                echo -e "\033[34msudo yum install -y $package\033[0m"
                sudo yum install -y "$package"
            fi
            ;;
        "fedora")
            if ! package_installed_dnf "$package"; then
                echo ""
                echo "_________________________________________________________"
                echo ""
                echo -e "\033[33mInstalling package $package...\033[0m"​⬤