#!/bin/bash

read -p "¿Deseas descargar el archivo? (y/n): " respuesta

if [ "$respuesta" == "y" ]; then
    # Descarga el archivo
    wget https://github.com/4rji/dotfiles/raw/c7e30ae701e2a4abf7df06554973374018acb1fa/comprimidos.tar.xz -O comprimidos.tar.xz

    # Descomprime el archivo
    tar -xJf comprimidos.tar.xz

    # Mueve el contenido a /opt/4rji/bin
    sudo mv comprimidos/* /opt/4rji/bin/

    # Limpia archivos temporales
    rm -rf comprimidos comprimidos.tar.xz

    echo "Archivos movidos exitosamente a /opt/4rji/bin/"
else
    echo "Operación cancelada."
fi
