#!/bin/bash

read -p "¿Deseas descargar el archivo? (y/n): " respuesta

if [ "$respuesta" == "y" ]; then
    # Descarga el archivo
    wget https://github.com/4rji/dotfiles/blob/6fc04f3780e5807a1a8e14843b37555096920ecf/comprimidos.tar.xz -O comprimidos.tar.xz
           
    # Descomprime el archivo
    tar -xJf comprimidos.tar.xz

    # Mueve el contenido a /opt/4rji/bin
    sudo mv comprimidos/* /opt/4rji/bin/

    # Limpia archivos temporales
    rm -rf comprimidos comprimidos.tar.xz

    echo "Archivos movidos exitosamente a /opt/4rji/bin/"
else
    echo "Operación cancelada."
fi
