#!/usr/bin/env bash

# Elevar privilegios si no es root
if [ "$EUID" -ne 0 ]; then
    exec sudo "$0" "$@"
fi

# Disable non-secure communication paths
systemctl --now mask ftpd
systemctl --now mask tftpd

# Remove telnet and FTP
if command -v apt >/dev/null 2>&1; then
    apt remove -y telnet ftp ftpd tftp talk talkd tftp tftpd
elif command -v yum >/dev/null 2>&1; then
    yum remove -y telnet ftp ftpd tftp talk talkd tftp tftpd
else
    echo "Package manager not found. Please remove telnet, FTP, and related daemons manually."
fi
