#!/bin/bash


echo ""
# Descargar el archivo desde la URL
wget -O neoconf https://raw.githubusercontent.com/4rji/4rji/main/neoconf

# Verificar si la descarga fue exitosa
if [ $? -eq 0 ]; then
    # Crear la carpeta si no existe
#    mkdir -p ~/.config/neofetch

    # Mover el archivo a la ubicaci  n deseada
    #mv ~/.config/neofetch/config.conf ~/.config/neofetch/config.conf.bk
    mkdir ~/.config/neofetch    
    mv neoconf ~/.config/neofetch/config.conf

    echo "El archivo se ha descargado y movido correctamente."
echo ""
    # Preguntar al usuario por el nuevo nombre
    read -p "Nombre del host nuevo: " nuevo_nombre

    # Reemplazar la palabra "casiton" en /opt/4rji/bin/nff con el nuevo nombre usando sudo
    sudo sed -i "s/casiton/$nuevo_nombre/g" /opt/4rji/bin/nff

    echo "Se ha realizado el reemplazo en /opt/4rji/bin/nff con el nuevo nombre."
else
    echo "Hubo un error al descargar el archivo."
fi

sudo cp /opt/4rji/bin/nff /opt/4rji/bin/wm



echo -e "\n\033[1;34m_________________________________________________________\033[0m\n"
echo "si no funciona hacerlo manual"
echo "Copiado a portapeles"
echo ""
echo "sudo sed -i \"s/casiton/$nuevo_nombre/g\" /opt/4rji/wm" 
echo "sudo sed -i \"s/casiton/$nuevo_nombre/g\" /opt/4rji/wm" | xclip -sel clip

echo -e "\n\033[1;34m_________________________________________________________\033[0m\n"

sudo mv /opt/4rji/bin/wm /usr/bin/wm