#!/bin/bash

#

echo -e "\n\033[1;35m_________________________________________________________\033[0m\n"
echo "Restart la shell"
echo "source ~/.zshrc"
echo -e "\n\033[1;35m_________________________________________________________\033[0m\n"


echo -e "\033[32mSet the server names? [S/n]):"
read respuesta

echo -e "\033[36m"
case $respuesta in
    "" | "S" | "s")
        ttyinicio
        sshexit
        wwinst
        ;;
    "n" | "N")

        ;;
    *)
        echo -e "\033[31mInvalid."
        ;;
esac

echo -e "\033[35m"
echo "ADVISORY: This script should be used for authorized penetration testing and/or educational purposes only. Any misuse of this software will not be the responsibility of the author or of any other collaborator. Use it at your own computers and/or with the computer owner's permission."
echo -e "\033[0m"

