#!/bin/bash


wget -O ~/.config/neofetch/config.conf https://raw.githubusercontent.com/4rji/4rji/main/neoconf


#sudo apt install neofetch -y
echo ""
# Descargar el archivo desde la URL


echo ""  
# Preguntar al usuario por el nuevo nombre
read -p "Nombre del host nuevo: " nuevo_nombre

# Reemplazar la palabra "casiton" en /usr/bin/nff con el nuevo nombre usando sudo
sudo cp /usr/bin/nff /usr/bin/wm
sudo sed -i "s/casiton/$nuevo_nombre/g" /usr/bin/wm

#sudo rm /usr/bin/neofetch
sudo cp /usr/bin/nff /usr/bin/wm

#sudo chattr +i /usr/bin/nff
#sudo chattr +i /usr/bin/wm

echo -e "\n\033[1;34m_________________________________________________________\033[0m\n"
echo "si no funciona hacerlo manual"
echo "Copiado a portapeles"
echo ""
echo "sudo sed -i \"s/casiton/$nuevo_nombre/g\" /usr/bin/wm" 
echo "sudo sed -i \"s/casiton/$nuevo_nombre/g\" /usr/bin/wm" | xclip -sel clip


echo -e "\n\033[1;34m_________________________________________________________\033[0m\n"

