#!/bin/bash

# Función para imprimir una línea de separación
print_separator() {
    echo -e "\033[1;35m_________________________________________________________\033[0m"
}

# Preguntar qué método de instalación desea utilizar
print_separator
echo -e "\033[1;32m¿Qué método desea utilizar para instalar Nessus?\033[0m"
echo -e "\033[1;33m1: Docker\033[0m"
echo -e "\033[1;34m2: dpkg\033[0m"
print_separator
read -p "\033[1;36mSeleccione una opción (1 o 2):\033[0m " opcion

if [ $opcion -eq 1 ]; then
    # Instala Nessus utilizando Docker
    docker pull tenable/nessus:latest-ubuntu

    # Preguntar si desea iniciar el contenedor Docker
    print_separator
    read -p "\033[1;36m¿Desea iniciar el contenedor Docker de Nessus? [s/n]:\033[0m " iniciar
    if [ "$iniciar" = "s" ]; then
        # Iniciar el contenedor Docker de Nessus
        docker run --name nessus -p 8834:8834 -d tenable/nessus:latest-ubuntu
        echo -e "\033[1;32mEl contenedor Docker de Nessus se ha iniciado.\033[0m"
        echo -e "\033[1;32mPuedes acceder a la interfaz web de Nessus desde tu navegador utilizando la dirección http://localhost:8834\033[0m"
        echo -e "\033[1;32mComando para iniciar el contenedor Docker de Nessus:\033[0m"
        echo -e "\033[1;34mdocker run --name nessus -p 8834:8834 -d tenable/nessus:latest-ubuntu\033[0m"
    fi

    # Crear alias en zsh y bash
    echo -e "\033[1;32mSe ha creado el alias 'nessus' para iniciar el contenedor Docker de Nessus en zsh y bash.\033[0m"
    echo -e "\033[1;34malias nessus='docker start nessus'\033[0m" >> ~/.zshrc
    echo -e "\033[1;34malias nessus='docker start nessus'\033[0m" >> ~/.bashrc
    
elif [ $opcion -eq 2 ]; then
    # Descargar el paquete de instalación de Nessus
    curl --request GET \
      --url 'https://www.tenable.com/downloads/api/v2/pages/nessus/files/Nessus-10.7.1-debian10_amd64.deb' \
      --output 'Nessus-10.7.1-debian10_amd64.deb'

    # Instala Nessus utilizando dpkg
    sudo dpkg -i Nessus-10.7.1-debian10_amd64.deb

    # Verifica el hash en la página oficial
    print_separator
    echo -e "\033[1;32mVerifica el hash en la página oficial que coincida: https://www.tenable.com/downloads/nessus?loginAttempted=true\033[0m"

    # Calcula y muestra el hash SHA-256 del archivo Nessus
    sha256sum Nessus-10.7.1-debian10_amd64.deb

    echo -e "\033[1;32mInstrucciones para iniciar Nessus:\033[0m"
    echo -e "\033[1;34mPara iniciar Nessus, simplemente escribe nessus o systemctl start nessusd.service\033[0m"

    # Crear alias en zsh y bash
    echo -e "\033[1;32mSe ha creado el alias 'nessus' para iniciar Nessus en zsh y bash.\033[0m"
    echo -e "\033[1;34malias nessus='systemctl start nessusd.service'\033[0m" >> ~/.zshrc
    echo -e "\033[1;34malias nessus='systemctl start nessusd.service'\033[0m" >> ~/.bashrc
    
else
    echo -e "\033[1;31mOpción no válida. Por favor, seleccione 1 o 2.\033[0m"
fi
