#!/usr/bin/env bash

# Menú de selección
echo "Seleccione el tipo de escaneo:"
echo "1) Escaneo básico (nmap -v --reason -sS)"
echo "2) Escaneo avanzado (nmap -A -O -sV)"
read -p "Ingrese su opción (1 o 2): " opcion

# Script 1 - AWK
awk -F '.' '{if ($1==ip1 && $2==ip2 && $3==ip3) printf(",%d",$4); else {if (NR>1) printf("\n"); printf("%s.%s.%s.%d", $1, $2, $3, $4); ip1=$1; ip2=$2; ip3=$3;}} END {printf("\n")}' ips.txt > resultado.txt

# Script 2 - NMAP
# Leer los datos del archivo resultado.txt
datos=$(cat resultado.txt)

# Selección del comando según la opción elegida
if [ "$opcion" = "1" ]; then
    comando="nmap -v -p-  --reason -sS -oX puertos.xml --stylesheet=\"https://svn.nmap.org/nmap/docs/nmap.xsl\" $datos"
elif [ "$opcion" = "2" ]; then
    comando="sudo nmap -p- -A -O -sV -oX puertos.xml --stylesheet=\"https://svn.nmap.org/nmap/docs/nmap.xsl\" $datos"
else
    echo "Opción inválida. Saliendo..."
    exit 1
fi

# Ejecutar el comando completo
eval "$comando"



