#!/usr/bin/env bash


echo ""
# Colors
GREEN="\e[32m"
BLUE="\e[34m"
RESET="\e[0m"
YELLOW="\e[33m"

echo -e "${BLUE}################# Explanation #################${RESET}"
echo -e "${GREEN}/sbin/nologin means that the account is not permitted an interactive shell login."
echo -e "UIDs below 1000 are generally for system/service accounts, while UIDs of 1000 and above are used for regular user accounts.${RESET}"

echo -e "\n\033[1;33m_________________________________________________________\033[0m\n"

echo ""
echo -e "${YELLOW}Command Execution:${RESET}"
echo -e "${BLUE}sudo egrep -v '^\+' /etc/passwd | awk -F: '\$3 >= 1000 {print}'${RESET}"
echo ""
echo -e "${BLUE}###############################################${RESET}\n"
echo ""

# Execute the command
sudo egrep -v '^\+' /etc/passwd | awk -F: '$3 >= 1000 {print}'
echo ""
