#!/bin/bash

# Definir los nombres de los servicios de red en cada distribución
ubuntu_service="network-manager"
debian_service="networking"
redhat_service="network"
arch_service="NetworkManager"
kali_service="network-manager"

# Función para reiniciar el servicio de red en Ubuntu
restart_ubuntu() {
    read -p "Ejecutar en Ubuntu (s/n): sudo systemctl restart $ubuntu_service " choice
    if [[ $choice == "s" ]]; then
        sudo systemctl restart $ubuntu_service
    fi
}

# Función para reiniciar el servicio de red en Debian/Ubuntu
restart_debian() {
    read -p "Ejecutar en Debian/Ubuntu (s/n): sudo systemctl restart $debian_service  " choice
    if [[ $choice == "s" ]]; then
        sudo service $debian_service restart
    fi
}

# Función para reiniciar el servicio de red en CentOS/RHEL
restart_redhat() {
    read -p "Ejecutar en CentOS/RHEL (s/n): sudo systemctl restart $redhat_service " choice
    if [[ $choice == "s" ]]; then
        sudo systemctl restart $redhat_service
    fi
}

# Función para reiniciar el servicio de red en Arch Linux
restart_arch() {
    read -p "Ejecutar en Arch Linux (s/n): sudo systemctl restart $arch_service " choice
    if [[ $choice == "s" ]]; then
        sudo systemctl restart $arch_service
    fi
}

# Función para reiniciar el servicio de red en Kali Linux
restart_kali() {
    read -p "Ejecutar en Kali Linux (s/n): sudo systemctl restart $kali_service " choice
    if [[ $choice == "s" ]]; then
        sudo systemctl restart $kali_service
    fi
}

# Función principal del script
main() {
    restart_ubuntu
    restart_debian
    restart_redhat
    restart_arch
    restart_kali
}

# Llamar a la función principal
main

