#!/usr/bin/env bash
set -e

REPO="https://github.com/Rootkit-Hunter/rkhunter.git"
DIR="rkhunter"

rm -rf "$DIR"
git clone "$REPO"
cd "$DIR"

# El installer.sh NO corre sin parametros
sudo bash installer.sh --layout default --install

# Ejecutar
sudo rkhunter --check --sk


echo ""
echo "sudo rkhunter --check --sk "

sudo tac /var/log/rkhunter.log | grep -m1 -B50 "System checks summary" | tac

