#!/bin/bash

echo ""
#si no funciona instalar : 
#pip3 install pycryptodome




# Lista de paquetes a instalar
paquetes=("python3" "python3-pip" )

# Función para verificar si un paquete está instalado (Debian/Ubuntu/Kali)
paquete_instalado_apt() {  
    dpkg -l "$1" | grep -q '^ii'  
}

# Función para verificar si un paquete está instalado (CentOS/RHEL)
paquete_instalado_yum() {
    yum list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Fedora)
paquete_instalado_dnf() {
    dnf list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Arch Linux)
paquete_instalado_pacman() {
    pacman -Qi "$1" &> /dev/null
}

# Detectar el sistema operativo
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
fi

# Instalar paquetes basados en el sistema operativo
for paquete in "${paquetes[@]}"; do
    case $OS in
        "debian"|"ubuntu"|"kali")
            if ! paquete_instalado_apt "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo apt-get install -y "$paquete"
            fi
            ;;
        "centos"|"rhel")
            if ! paquete_instalado_yum "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo yum install -y "$paquete"
            fi
            ;;
        "fedora")
            if ! paquete_instalado_dnf "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo dnf install -y "$paquete"
            fi
            ;;
        "arch")
            if ! paquete_instalado_pacman "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo pacman -S --noconfirm "$paquete"
            fi
            ;;
        *)
            ;;
    esac
done








echo -e "\033[1;32mEl comando que este script ejecuta es:\033[0m"
    echo ""
    echo -e "\033[1;33mpython3 -m http.server 80\033[0m"










echo ""
echo -e "\033[1;34m_________________________________________________________\033[0m"
#echo ""

#descomprimir linpeas porque github no me deja subirlo sin encriptar
linpi
#cambiando permisos a chmod +x 
chmod +x  /tmp/apache/linpeas.sh
chmod +x  /tmp/apache/winPEASx64.exe
chmod +x  /tmp/apache/winPEASx86.exe



# Variables para opciones predeterminadas
default_port="80"
port=$default_port

# Directorio de destino para los archivos Apache
destination_dir="/tmp/apache"

# Archivo de lista de nombres de archivos
file_list="/usr/bin/listaapache"

# Pregunta combinada
read -p "¿Deseas utilizar un puerto diferente al predeterminado ($default_port)? [s/N] " custom_port
custom_port="${custom_port:-n}"

if [[ $custom_port =~ ^[Ss]$ ]]; then
    # Solicitar el puerto personalizado
    read -p "Por favor, introduce el puerto deseado: " port
fi

# Copiar archivos de la listaapache a /tmp/apache
if [ ! -d "$destination_dir" ]; then
    mkdir -p "$destination_dir"
fi

while IFS= read -r filename; do
    file_path=$(find /usr/bin/ -name "$filename" 2>/dev/null)
    if [ -n "$file_path" ]; then
        cp "$file_path" "$destination_dir"
    else
        
        echo -e "\033[0;31mNo se encontro el archivo $filename en /usr/bin\033[0m"
    fi
done < "$file_list"

echo ""
echo -e "\033[0;34mArchivos copiados a $destination_dir\033[0m"
ls $destination_dir
echo ""


# Iniciar el servidor HTTP de Python en /tmp/apache
if [[ $port =~ ^[0-9]+$ ]]; then
    cd "$destination_dir"
    echo ""
    echo -e "${BLUE}Iniciando servidor HTTP de Python en la ruta $destination_dir:$port${NC}"
#    ip -4 addr show | awk '/inet/ && !/127.0.0.1/ {split($2, a, "/"); printf "\t\t\t\t%s: %s\n", $NF, a[1]}'
    ip -4 addr show | awk '/inet/ && !/127.0.0.1/ {split($2, a, "/"); printf "\033[1;31m\t\t\t\t%s: %s\n\033[0m", $NF, a[1]}'

    echo ""
    python3 -m http.server $port
else
    echo -e "${RED}El puerto ingresado no es valido.${NC}"
fi
