#!/bin/bash

echo ""
echo -e "\033[1;34m_________________________________________________________\033[0m"
echo ""
# Función para mostrar el mensaje de ayuda y preguntar si desea continuar
show_help_and_confirm() {
    echo ""
    echo -e "\033[1;32mEl comando que este script ejecuta es:\033[0m"
    echo ""
    echo -e "\033[1;33mpython3 -m http.server 80\033[0m"
    echo ""
    echo ""
    echo -e "\033[1;34m_________________________________________________________\033[0m"
    echo ""

    # Preguntar al usuario si desea continuar
    read -n1 -p "Continuar el script? Cancelar [c]  " response
    echo ""  # Añadir una nueva línea para la salida

    # Convertir la respuesta a minúsculas y evaluar
    case "$response" in
    *) echo "Continuando..." ;;
    esac
}

# Variables para opciones predeterminadas
default_port="80"
port=$default_port

# Directorio de destino para los archivos Apache
destination_dir="/tmp/apache"

# Archivo de lista de nombres de archivos
file_list="/usr/bin/listaapache"

# Pregunta combinada
read -p "¿Deseas utilizar un puerto diferente al predeterminado ($default_port)? [s/N] " custom_port
custom_port="${custom_port:-n}"

if [[ $custom_port =~ ^[Ss]$ ]]; then
    # Solicitar el puerto personalizado
    read -p "Por favor, introduce el puerto deseado: " port
fi

# Copiar archivos de la listaapache a /tmp/apache
if [ ! -d "$destination_dir" ]; then
    mkdir -p "$destination_dir"
fi
while IFS= read -r filename; do
    file_path=$(find /usr/bin/ -name "$filename" 2>/dev/null)
    if [ -n "$file_path" ]; then
        cp "$file_path" "$destination_dir"
    else
        echo -e "${RED}No se encontró el archivo $filename en /usr/bin.${NC}"
    fi
done < "$file_list"
echo -e "${BLUE}Archivos de listaapache copiados a $destination_dir.${NC}"

# Iniciar el servidor HTTP de Python en /tmp/apache
if [[ $port =~ ^[0-9]+$ ]]; then
    cd "$destination_dir"
    echo -e "${BLUE}Iniciando servidor HTTP de Python en la ruta $destination_dir:$port${NC}"
    python3 -m http.server $port
else
    echo -e "${RED}El puerto ingresado no es válido.${NC}"
fi
