#!/usr/bin/env bash

# Ruta al archivo que contiene la lista de usuarios
user_file="$HOME/users-pw"

echo ""
echo "========================================================="
echo "                      User Shell Manager                "
echo "========================================================="
echo ""

# Verificar si el archivo de usuarios existe
if [[ ! -f "$user_file" ]]; then
    echo -e "\033[1;31mUser file $user_file not found. Exiting.\033[0m"
    exit 1
fi

# Mostrar información de los usuarios de la lista en /etc/passwd
echo -e "\033[1;34mChecking user details in /etc/passwd for the listed users:\033[0m"

echo -e "\n\033[1;34m_________________________________________________________\033[0m\n"
echo ""
while read -r user; do
    if grep -q "^$user:" /etc/passwd; then
        #echo -e "\033[1;32mFound user: $user\033[0m"
        grep "^$user:" /etc/passwd
    else
        echo -e "\033[1;31mUser $user not found in /etc/passwd. Skipping.\033[0m"
    fi
done < "$user_file"
echo ""

echo -e "\n\033[1;31m_________________________________________________________\033[0m\n"


# Preguntar si desea continuar para asignar `nologin`
echo -e "\033[1;33mDo you want to set 'nologin' shell for the listed users?\033[0m"
echo ""
read -rp "[Press 'y' to proceed or Enter to cancel]: " response
response="${response,,}" # Convertir a minúsculas

if [[ "$response" == "y" ]]; then
    echo ""
    echo "========================================================="
    echo "                   Processing Users                     "
    echo "========================================================="
    echo ""

    # Procesar usuarios para asignarles 'nologin'
    while read -r user; do
        if id "$user" &>/dev/null; then
            #echo -e "\033[1;32mSetting nologin for user: $user\033[0m"
            sudo usermod -s /usr/sbin/nologin "$user"
        else
            echo -e "\033[1;31mUser $user does not exist. Skipping.\033[0m"
        fi
    done < "$user_file"
    echo ""
    echo "========================================================="
    echo "              All users have been processed             "
    echo "========================================================="
    echo ""
else
    echo ""
    echo -e "\033[1;31mOperation canceled. No changes were made.\033[0m"
    echo ""
fi

echo ""
echo -e "\033[1;36mADVISORY: This script should be used for authorized penetration testing and/or educational purposes only. Any misuse of this software will not be the responsibility of the author or of any other collaborator. Use it at your own computers and/or with the computer owner's permission.\033[0m"
echo ""
