#!/bin/bash

# Definir las ubicaciones de las carpetas en el servidor y en tu máquina local
carpeta_servidor="/home/ass/Documents/GitHub/4rji/4rjinotes/htb"
carpeta_local="/home/nat/Documents/GitHub/4rji/4rjinotes/htb"

# Sincronizar las carpetas utilizando rsync
rsync -avz asskemu:$carpeta_servidor/ $carpeta_local

echo "¡Sincronización completada!"
