#!/usr/bin/env bash

# Función para mostrar mensajes (en este script principal)
echo_msg() {
  echo ""
  echo "=========================================================="
  echo "$1"
  echo "=========================================================="
  echo ""
}

echo ""
echo "_________________________________________________________"
echo ""

read -p $'\033[36m  Ingresa la IP del servidor remoto: \033[0m' IP

echo ""
echo "_________________________________________________________"
echo ""

read -p $'\033[35m  Ingresa el usuario remoto: \033[0m' USUARIO

echo ""
echo "_________________________________________________________"
echo ""

read -p $'\033[32m  Ingresa el puerto SSH remoto [22 por defecto]: \033[0m' PUERTO

if [ -z "$PUERTO" ]; then
  PUERTO=22
fi

cat << EOF > conexion.sh
#!/usr/bin/env bash

# Función para mostrar mensajes
echo_msg() {
  echo ""
  echo "=============================================="
  echo -e "\$1"
  echo "=============================================="
  echo ""
}

IP="$IP"
USUARIO="$USUARIO"
PUERTO=$PUERTO

if pgrep -f "ssh.*-R 2222:localhost:22.*\$USUARIO@\$IP" > /dev/null 2>&1; then
  echo_msg "\033[34m  La conexión SSH ya está activa.\033[0m"
else
  echo_msg "\033[31m  No se encontró la conexión. Iniciando...\033[0m"

  SSH_CMD="ssh -N -f -R 2222:localhost:22 -p \$PUERTO \$USUARIO@\$IP"

  echo ""
  echo "_________________________________________________________"
  echo ""
  echo -e "\033[33m  Ejecutando: \$SSH_CMD\033[0m"
  echo ""

  \$SSH_CMD

  echo_msg "\033[36m  Conexión SSH establecida.\033[0m"
fi
EOF

chmod +x conexion.sh

echo ""
echo "_________________________________________________________"
echo ""

echo -e "\033[33m  El script 'conexion.sh' se ha creado con la configuración proporcionada.\033[0m"
echo -e "\033[35m  Puedes agregarlo al crontab para que se ejecute cada 5 minutos si lo deseas.\033[0m"
echo ""
