#!/usr/bin/env bash

# Paso 1: Eliminar líneas conflictivas del banner anterior en /etc/ssh/sshd_config
sudo sed -i '/Banner no/d' /etc/ssh/sshd_config

# Paso 2: Habilitar la característica de pre login banner en sshd
sudo sed -i 's/#Banner/Banner/g' /etc/ssh/sshd_config

# Paso 3: Crear el archivo de banner de inicio de sesión con el nuevo mensaje sin asteriscos laterales
sudo tee /etc/ssh/sshd-banner > /dev/null << 'EOF'

                              Rubber Ducks inc.

**********************************************************************

UNAUTHORIZED ACCESS TO THIS DEVICE IS PROHIBITED

You must have explicit, authorized permission to access or configure this system.
Unauthorized access is not tolerated under any circumstances.

All network activity on this device is continuously monitored, logged, and analyzed.
Any attempt to breach or misuse this system may result in severe civil and/or criminal penalties.

Activity logs and other recorded information may be used to investigate, prosecute, and bring legal action against unauthorized users.

**********************************************************************
                             
                             Rubber Ducks inc.

EOF

# Paso 4: Agregar la línea 'Banner /etc/ssh/sshd-banner' a sshd_config si no existe
if ! sudo grep -q "Banner /etc/ssh/sshd-banner" /etc/ssh/sshd_config; then
  echo "Banner /etc/ssh/sshd-banner" | sudo tee -a /etc/ssh/sshd_config > /dev/null
  echo "¡Listo! El banner de pre login de OpenSSH ha sido configurado."
fi

# Paso 5: Reiniciar el servicio sshd para aplicar los cambios
sudo systemctl restart ssh

# Alias para editar el banner con nano en futuras ocasiones
echo "alias bannere='sudo nano /etc/ssh/sshd-banner'" >> ~/.zshrc