#!/bin/bash

echo ""
echo "ssh-copy-id -i ~/.ssh/id_ed25519.pub -p puerto_ssh user@IP  "

echo ""
echo -e "\033[1;34m_________________________________________________________\033[0m"
echo ""
# Función para mostrar el mensaje de ayuda y preguntar si desea continuar
show_help_and_confirm() {
    echo ""
    echo -e "\033[1;32mEl comando que este script ejecuta es:\033[0m"
    echo ""
    echo -e "\033[1;33mssh-copy-id -i ~/.ssh/id_ed25519.pub -p puerto_ssh user@IP  \033[0m"
    echo ""
    echo ""
echo -e "\033[1;34m_________________________________________________________\033[0m"
    echo ""

    # Preguntar al usuario si desea continuar
    read -n1 -p "Continuar el script?  Cancel [c]  " response
    echo ""  # Añadir una nueva línea para la salida

    # Convertir la respuesta a minúsculas y evaluar
    case "$response" in
    *) echo "Continuando..." ;;
    esac
}

# Verificar si se pasó el argumento -h
if [ "$1" == "-h" ]; then
    show_help_and_confirm
fi

# Generar la clave SSH
ssh-keygen -t ed25519

# Obtener el cliente en formato usuario@IP y el puerto SSH
echo "Ingresa el cliente en formato 'usuario@IP':"
read cliente

echo "Ingresa el puerto SSH:"
read puerto_ssh

# Copiar la clave SSH al host
ssh-copy-id -i ~/.ssh/id_ed25519.pub -p "$puerto_ssh" "$cliente"
