#!/bin/bash

# Pide el nombre del servidor
read -p "Ingrese el nombre del servidor: " server_name

# Copia el script wm-exit a /usr/bin
sudo cp /opt/4rji/bin/wm-exit /usr/bin/wm-exit

# Modifica el script wm-exit para actualizar la variable con el nombre del servidor
# Asegúrate de que el uso de sed coincida exactamente con cómo está formateado en el script original
sudo sed -i "s/echo \"nserver\" | figlet/echo \"$server_name\" | figlet/" /usr/bin/wm-exit

# Agrega wm-exit al archivo zlogout para Zsh
echo "/usr/bin/wm-exit" >> ~/.zlogout

echo "Configuración de salida SSH completada."
