#!/bin/bash

# Ask for the server name
read -p "Enter the server name: " server_name

# Copy the wm-exit script to /usr/bin
sudo cp /opt/4rji/bin/wm-exit /usr/bin/wm-exit

# Modify the wm-exit script to update the nserver variable
sudo sed -i "s/\(Server: \)nserver/\1$server_name/" /usr/bin/wm-exit

# Add wm-exit to the zlogout for Zsh
echo "/usr/bin/wm-exit" >> ~/.zlogout

echo "SSH exit configured."
