#!/bin/bash

# Directory where the SSH config file is stored
ssh_config_file="$HOME/.ssh/config"

# Check if the SSH config file exists
if [ ! -f "$ssh_config_file" ]; then
    echo -e "\n\e[33mError: The SSH config file does not exist.\e[0m\n"
    exit 1
fi

# Extract host names and IP addresses from the config file
hosts_with_ip=$(awk '/^Host / { host = $2 } /^ +HostName / { print host, $2 }' "$ssh_config_file")


echo -e "\n\033[1;35m_________________________________________________________\033[0m\n"
# Display the list of hosts with their IP addresses
echo -e "\e[34mList of available hosts:\e[0m"
echo ""
echo "$hosts_with_ip" | awk '{print NR".",$1, $2}'

# Ask the user which host they want to connect to
echo -e "\n\033[1;35m_________________________________________________________\033[0m\n"
read -p $'\n\e[33mEnter the number of the host you want to connect to: \e[0m' chosen_host_number

# Validate user input
if ! [[ "$chosen_host_number" =~ ^[0-9]+$ ]]; then
    echo -e "\n\e[31mError: Please enter a valid number.\e[0m\n"
    exit 1
fi

# Extract the chosen host and its IP address
chosen_host=$(echo "$hosts_with_ip" | sed -n "${chosen_host_number}p" | awk '{print $1}')
chosen_ip=$(echo "$hosts_with_ip" | sed -n "${chosen_host_number}p" | awk '{print $2}')

# Check if the chosen host exists in the list
if [ -z "$chosen_host" ]; then
    echo -e "\n\e[31mError: The chosen host number '$chosen_host_number' is not in the list.\e[0m\n"
    exit 1
fi

# Connect to the chosen host
echo -e "\n\e[33mConnecting to $chosen_host ($chosen_ip)...\e[0m\n"
ssh "$chosen_host"

