#!/bin/bash
echo -e "\n\033[1;35m_________________________________________________________\033[0m\n"
archivo_config="$HOME/.ssh/config"  # Ruta al archivo config de SSH

nombres_hosts=()
while IFS= read -r linea; do
    if [[ $linea == Host* ]]; then
        nombre_host=$(echo "$linea" | awk '{print $2}')
        nombres_hosts+=("$nombre_host")
    fi
done < "$archivo_config"

echo "List of available hosts:"
for (( i=0; i<"${#nombres_hosts[@]}"; i++ )); do
    echo "$(($i+1)). ${nombres_hosts[$i]}"
done

# Ask the user which host they want to connect to
echo -e "\n\033[1;35m_________________________________________________________\033[0m\n"
read -p $'\n\e[33mEnter the number of the host you want to connect to: \e[0m' chosen_host_number

# Validate user input
if ! [[ "$chosen_host_number" =~ ^[0-9]+$ ]]; then
    echo -e "\n\e[31mError: Please enter a valid number.\e[0m\n"
    exit 1
fi

# Check if the chosen host number is within range
if ((chosen_host_number < 1 || chosen_host_number > ${#nombres_hosts[@]})); then
    echo -e "\n\e[31mError: Please enter a number within the range.\e[0m\n"
    exit 1
fi

# Connect to the chosen host
chosen_host=${nombres_hosts[$(($chosen_host_number-1))]}
echo -e "\n\e[33mConnecting to $chosen_host...\e[0m\n"
ssh "$chosen_host"
