#!/usr/bin/env python3
import subprocess
from datetime import datetime

counter = 0

while True:
    # Ejecuta el comando 'sshmonitor'. Asegúrate de que esté en el PATH.
    subprocess.run(["sshmonitor"])
    
    counter += 1
    # Obtiene la fecha y hora actuales
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    print(f"Scan number: {counter} | Timestamp: {current_time}")