#!/usr/bin/env python3
import subprocess
from datetime import datetime

counter = 0

while True:
    # Execute the 'sshmonitor' command. Make sure 'sshmonitor' is in the PATH.
    subprocess.run(["sshmonitor"])
    
    counter += 1
    # Get the current date and time
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Print the scan number and timestamp with immediate flush
    print(f"Scan number: {counter} | Timestamp: {current_time}", flush=True)