#!/bin/bash

# Define la URL de descarga
URL="https://raw.githubusercontent.com/4rji/archivos-b/main/config"

# Obtén la fecha actual en formato año-mes-día
DATE=$(date +%Y-%m-%d)

# Backup del archivo de configuración SSH
cp ~/.ssh/config ~/.ssh/config_$DATE

# Descarga el nuevo archivo de configuración de SSH
wget -O /tmp/config $URL

# Combina los archivos de configuración sin duplicados
awk '!seen[$0]++' ~/.ssh/config /tmp/config > /tmp/config_combined

# Reemplaza el archivo de configuración SSH con el combinado
mv /tmp/config_combined ~/.ssh/config


echo -e "\n\033[1;37m_________________________________________________________\033[0m\n"


