#!/bin/bash

# Ensure a subnet is provided as an argument
if [ $# -ne 1 ]; then
    echo "Please provide a subnet as an argument. Example: ./script.sh 192.168.1"
    exit 1
fi

echo "_________________________________________________________"
echo ""

subnet="$1"
tempfile=$(mktemp) # Create a temporary file

# Pings each IP in the subnet and displays the output
for ip in $(seq 1 254); do
    ping -c 1 "$subnet.$ip" | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" | tee -a $tempfile >/dev/null &
done

echo "Scanning ..."
#wait # Wait for all background processes to finish

echo ""
echo "Done."
echo ""

# Display a list of found IPs and check for matching hosts in ~/.ssh/config
echo "List of IP addresses and corresponding host names if available:"
echo ""
counter=1
while read -r ip; do
    # Extract the hostname matching the IP from ~/.ssh/config
    host_name=$(grep -B 1 "$ip" ~/.ssh/config | grep "Host " | awk '{print $2}')
    if [[ -n "$host_name" ]]; then
        echo "$counter- $ip - $host_name"
    else
        echo "$counter- $ip - Host name not found"
    fi
    ((counter++))
done < $tempfile

echo ""
echo "_________________________________________________________"
echo ""

# Ask for the number to scan
read -p "Which number from the list to scan: " selected_number
echo ""
selected_ip=$(sed "${selected_number}q;d" $tempfile | awk '{print $1}')
read -n1 -p "Execute nmap expo to $selected_ip? [y/n]: " execute_expo

if [[ $execute_expo =~ ^[Yy]$ ]]; then
    expo $selected_ip
else
    echo "Expo command was not executed."
fi

# Remove the temporary file
rm $tempfile

echo ""
echo "*** Caution: This script is made for /24 ***"
echo ""
