#!/bin/bash

# Ensure a subnet is provided as an argument
if [ $# -ne 1 ]; then
    echo "Please provide a subnet as an argument. Example: ./script.sh 192.168.1"
    exit 1
fi

echo "_________________________________________________________"
echo ""

#sleep 0.5

subnet="$1"
tempfile=$(mktemp) # Create a temporary file

# Pings each IP in the subnet and displays the output
for ip in $(seq 1 254); do
    ping -c 1 "$subnet.$ip" | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" | tee -a $tempfile >/dev/null &
done
echo "Scanning ..."
#wait # Wait for all background processes to finish

echo ""
echo "Done."
echo ""

# Display a list of found IPs
echo "List of IP addresses found:"
echo ""
awk '{ print NR "- " $0 }' $tempfile

echo ""
echo "_________________________________________________________"
echo ""

# Asks the user if they want to run nmap for a specific IP
read -n1 -p "Run Nmap on an IP? [y/n] " choice
echo ""
echo ""

if [[ $choice =~ ^[Yy]$ ]]; then
    read -p "Which number from the list: " selected_number
    echo ""
    selected_ip=$(sed "${selected_number}q;d" $tempfile)
    read -n1 -p "Execute nmap expo to $selected_ip? [y/n]: " execute_expo

    if [[ $execute_expo =~ ^[Yy]$ ]]; then
        expo $selected_ip
    else
        echo "Expo command was not executed."
    fi
else
    echo "Exiting the script."
fi

# Remove the temporary file
rm $tempfile

echo ""
echo "*** Caution: This script is made for /24 ***"
echo ""
