#!/usr/bin/env bash
echo ""

echo -e "\033[1;33mReminder: Keep track of both tokens for future use.\033[0m"
echo ""
sleep 1

# Function to install Tailscale automatically
function install_tailscale {
    echo ""
    echo "_________________________________________________________"
    echo ""
    echo -e "\033[1;35mStarting Tailscale installation...\033[0m"
    echo ""
    echo "_________________________________________________________"
    echo ""
    
    curl -fsSL https://tailscale.com/install.sh | sh

    echo ""
    echo "_________________________________________________________"
    echo ""
    echo -e "\033[1;36mInstallation complete.\033[0m"
    echo ""
    echo -e "\033[1;33mNow register your machine with your auth key:\033[0m"
    echo ""
    echo -e "\033[1;32msudo tailscale up --authkey \$tailsKey --hostname MachineName\033[0m"
    echo ""
    echo "___ tailip = IPs. /   tails = status________________________________________"
    echo "sudo tailscale set --accept-dns=false   "
    
    echo ""
}

# Main execution
install_tailscale