#!/bin/bash
#new
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

rm .tmux.conf.local
rm .tmux.conf


#old conf
#wget https://raw.githubusercontent.com/4rji/4rji/main/tmux/.tmux.conf

#new estofado

wget https://raw.githubusercontent.com/4rji/estofado/main/tmux/.tmux.conf
mv .tmux.conf ~/.tmux.conf


#new with dotfiles
#wget https://raw.githubusercontent.com/4rji/dotfiles/main/tmux.conf
#mv tmux.conf ~/.tmux.conf


tmux source ~/.tmux.conf

echo -e "\n\033[1;31m_________________________________________________________\033[0m\n"
echo ""
echo "Open tmux and install the plugins with Control B, then Shift I ( i of install )"
echo -e "\n\033[1;31m_________________________________________________________\033[0m\n"