#!/bin/bash
#new
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

rm .tmux.conf.local
rm .tmux.conf


#old conf
#wget https://raw.githubusercontent.com/4rji/4rji/main/tmux/.tmux.conf

#new estofado
wget https://raw.githubusercontent.com/4rji/estofado/main/tmux/.tmux.conf

mv .tmux.conf ~/.tmux.conf



tmux source ~/.tmux.conf
