#!/bin/bash

# Define the directory
DIR="/home/nat/Documents/GitHub/bina/binarios"

# Calculate total lines
TOTAL_LINES=$(wc -l "$DIR"/* 2>/dev/null | awk 'END{print $1}' | numfmt --grouping)

# Count total scripts (files)
TOTAL_SCRIPTS=$(find "$DIR" -type f | wc -l | numfmt --grouping)

# Define colors
COLOR_RESET="\033[0m"
COLOR_BLUE="\033[34m"
COLOR_GREEN="\033[32m"

# Print results in a table
echo -e "${COLOR_BLUE}=============================="
echo -e "         Statistics"
echo -e "==============================${COLOR_RESET}"
echo -e "${COLOR_GREEN}Total Lines: ${COLOR_RESET}$TOTAL_LINES"
echo -e "${COLOR_GREEN}Total Scripts: ${COLOR_RESET}$TOTAL_SCRIPTS"
echo -e "${COLOR_BLUE}==============================${COLOR_RESET}"

sleep .5

find /home/nat/Documents/GitHub/bina/binarios -type f | fzf --preview 'bat --color=always --style=plain {}'

