#!/usr/bin/env bash
set -e

# Install PowerShell on Ubuntu
sudo apt update
sudo apt install -y wget apt-transport-https software-properties-common

wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb

sudo apt update
sudo apt install -y powershell

# Show version
pwsh -Command '$PSVersionTable.PSVersion'
