#!/bin/bash

# Función para iniciar la red predeterminada
function iniciar_network {
    echo "Iniciando la red predeterminada..."
    sudo virsh net-start default
    echo "La red predeterminada ha sido iniciada."
}

# Función para mostrar el menú de opciones y gestionar las máquinas virtuales
function gestionar_vms {
    while true; do
        echo "_________________________________________________________"
        echo ""
        echo "Listando todas las máquinas virtuales:"
        echo ""
        mapfile -t vms < <(sudo virsh list --all | awk 'NR>2 {print NR-2 ")\t" $2 "\t" $3}')
        printf '%s\n' "${vms[@]}"
        echo "_________________________________________________________"
        echo ""

        read -n1 -p "Ingresa el número de la máquina virtual que deseas gestionar: " vm_number
        echo ""
        selected_vm=$(echo "${vms[vm_number-1]}" | awk '{print $2}')
        echo "_________________________________________________________"
        echo ""
        echo "Has seleccionado la máquina: $selected_vm"
        echo "_________________________________________________________"
        echo ""

        echo "¿Qué acción deseas realizar?"
        echo ""
        echo "1) Consola"
        echo "2) START vm"
        echo "3) STOP vm"
        echo "4) Forzar apagado (destroy)"
        echo "5) Borrar VM y su almacenamiento (undefine)"
        echo "6) Virsh Viewer"
        echo "7) Iniciar Network"
        echo "_________________________________________________________"
        read -n1 -p "Selecciona una opción (1/2/3/4/5/6/7): " action
        echo ""
        echo "_________________________________________________________"

        case $action in
            1)
                echo "Accediendo a la consola de $selected_vm. Para salir, presiona Ctrl+]"
                sudo virsh console "$selected_vm"
                ;;
            2)
                echo "Iniciando $selected_vm..."
                sudo virsh start "$selected_vm"
                sleep 2
                ;;
            3)
                echo "Deteniendo $selected_vm..."
                sudo virsh shutdown "$selected_vm"
                sleep 2
                ;;
            4)
                echo "Forzando apagado (destroy) de $selected_vm..."
                sudo virsh destroy "$selected_vm"
                sleep 2
                ;;
            5)
                echo "Borrando $selected_vm y su almacenamiento (undefine)..."
                sudo virsh undefine "$selected_vm" --remove-all-storage
                sleep 2
                ;;
            6)
                echo "Abriendo $selected_vm en Virsh Viewer..."
                sudo virt-viewer "$selected_vm" &
                ;;
            7)
                iniciar_network
                ;;
            *)
                echo "Opción no válida. Saliendo..."
                exit 1
                ;;
        esac
    done
}

# Llamada a la función para gestionar las máquinas virtuales
gestionar_vms
