#!/usr/bin/env bash

reset
echo ""

# Verificar si se proporcionó el nombre de la interfaz
if [ -z "$1" ]; then
  echo "Uso: $0 <interfaz_wireguard>"
  exit 1
fi

INTERFACE=$1
CONFIG_FILE="/etc/wireguard/$INTERFACE.conf"

# Verificar si systemd-resolved está activo
if ! systemctl is-active --quiet systemd-resolved; then
  echo "systemd-resolved no está activo. ¿Desea activarlo? (s/n)"
  read -n1 activate_resolved
  echo ""
  if [ "$activate_resolved" = "s" ]; then
    sudo systemctl start systemd-resolved
  fi
fi

# Función para mostrar el menú
show_menu() {
  echo ""
  echo -e "\033[36m_________________________________________________________\033[0m"
  echo ""
  echo -e "\033[34mSelecciona una opción:\033[0m"
  echo -e "\033[32mc) Conectar\033[0m"
  echo -e "\033[33md) Desconectar\033[0m"
  echo -e "\033[35mr) Reconectar\033[0m"
  echo -e "\033[31ms) Mostrar estado de la conexión\033[0m"
  echo -e "\033[36mm) Modificar archivo de configuración\033[0m"
  echo -e "\033[36mq) Salir\033[0m"
  echo ""
  echo -e "\033[36m_________________________________________________________\033[0m"
  echo ""
}

# Verificar si nano está instalado
if ! command -v nano &> /dev/null; then
  echo -e "\033[31mError: El editor nano no está instalado. Por favor, instálalo o usa otro editor.\033[0m"
  exit 1
fi

# Bucle principal
while true; do
  show_menu
  echo -e "\033[34mPresiona la tecla correspondiente para elegir una opción [c/d/r/s/m/q]: \033[0m"

  # Leer una sola tecla sin necesidad de presionar Enter
  read -n1 choice
  echo ""

  case $choice in
    c)
      echo -e "\033[32m\nConectando a la interfaz WireGuard: $INTERFACE\033[0m"
      sudo wg-quick up $INTERFACE
      ;;
    d)
      echo -e "\033[33m\nDesconectando la interfaz WireGuard: $INTERFACE\033[0m"
      sudo wg-quick down $INTERFACE
      ;;
    r)
      echo -e "\033[35m\nReconectando la interfaz WireGuard: $INTERFACE\033[0m"
      sudo wg-quick down $INTERFACE && sudo wg-quick up $INTERFACE
      ;;
    s)
      echo -e "\033[31m\nMostrando el estado de la interfaz WireGuard: $INTERFACE\033[0m"
      sudo wg show $INTERFACE
      ;;
    m)
      echo -e "\033[36m\nModificando archivo de configuración para: $INTERFACE\033[0m"
      sudo nano $CONFIG_FILE
      ;;
    q)
      echo -e "\033[36m\nSaliendo...\033[0m"
      exit 0
      ;;
    *)
      echo -e "\033[31m\nOpción inválida. Por favor, selecciona una opción válida [c/d/r/s/m/q].\033[0m"
      ;;
  esac
done
