#!/usr/bin/env bash

if [[ $# -ne 1 ]]; then
    echo -e "\n[!] Uso: $0 <direccion-ip>\n"
    exit 1
fi

ip_address="$1"

ttl=$(ping -c 1 "$ip_address" 2>/dev/null | grep -oiE 'ttl=[0-9]+' | cut -d= -f2)

if [[ -z "$ttl" ]]; then
    echo -e "\n[!] No se pudo obtener TTL de $ip_address\n"
    exit 1
fi

if [[ $ttl -le 64 ]]; then
    os_name="Linux"
elif [[ $ttl -le 128 ]]; then
    os_name="Windows"
else
    os_name="Not Found"
fi

echo -e "\n$ip_address (ttl -> $ttl): $os_name\n"
