#!/usr/bin/env bash


#!/bin/bash

# Lista de paquetes a instalar
paquetes=("bat" "batcat" "xclip")

# Función para verificar si un paquete está instalado (Debian/Ubuntu/Kali)
paquete_instalado_apt() {
    dpkg -l "$1" | grep -q '^ii'  
}

# Función para verificar si un paquete está instalado (CentOS/RHEL)
paquete_instalado_yum() {
    yum list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Fedora)
paquete_instalado_dnf() {
    dnf list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Arch Linux)
paquete_instalado_pacman() {
    pacman -Qi "$1" &> /dev/null
}

# Detectar el sistema operativo
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
fi

# Instalar paquetes basados en el sistema operativo
for paquete in "${paquetes[@]}"; do
    case $OS in
        "debian"|"ubuntu"|"kali")
            if ! paquete_instalado_apt "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo apt-get install -y "$paquete"
            fi
            ;;
        "centos"|"rhel")
            if ! paquete_instalado_yum "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo yum install -y "$paquete"
            fi
            ;;
        "fedora")
            if ! paquete_instalado_dnf "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo dnf install -y "$paquete"
            fi
            ;;
        "arch")
            if ! paquete_instalado_pacman "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo pacman -S --noconfirm "$paquete"
            fi
            ;;
        *)
            ;;
    esac
done


if [ $# -ne 1 ]; then
  echo "Uso: $0 <comando>"
  exit 1
fi

comando="$1"

# Busca la ubicación del comando binario
ruta_comando=$(which "$comando")

if [ -z "$ruta_comando" ]; then
  echo "El comando '$comando' no se encontró en el sistema."
  exit 1
fi

# Muestra la ubicación del comando binario
echo "Ubicación de $comando:"
echo "$ruta_comando"

# Copia la ubicación del comando al portapapeles
echo "$ruta_comando" | xclip -selection clipboard

# Muestra el contenido del archivo binario
#cat "$ruta_comando"
batcat -l rb --paging=never "$ruta_comando"
#y
