#!/bin/bash


# Lista de paquetes a instalar
paquetes=("wireguard" "resolvconf" )

# Función para verificar si un paquete está instalado (Debian/Ubuntu/Kali)
paquete_instalado_apt() {
    dpkg -l "$1" | grep -q '^ii'  
}

# Función para verificar si un paquete está instalado (CentOS/RHEL)
paquete_instalado_yum() {
    yum list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Fedora)
paquete_instalado_dnf() {
    dnf list installed "$1" &> /dev/null
}

# Función para verificar si un paquete está instalado (Arch Linux)
paquete_instalado_pacman() {
    pacman -Qi "$1" &> /dev/null
}

# Detectar el sistema operativo
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
fi

# Instalar paquetes basados en el sistema operativo
for paquete in "${paquetes[@]}"; do
    case $OS in
        "debian"|"ubuntu"|"kali")
            if ! paquete_instalado_apt "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo apt-get install -y "$paquete"
            fi
            ;;
        "centos"|"rhel")
            if ! paquete_instalado_yum "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo yum install -y "$paquete"
            fi
            ;;
        "fedora")
            if ! paquete_instalado_dnf "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo dnf install -y "$paquete"
            fi
            ;;
        "arch")
            if ! paquete_instalado_pacman "$paquete"; then
                echo "Instalando el paquete $paquete..."
                sudo pacman -S --noconfirm "$paquete"
            fi
            ;;
        *)
            ;;
    esac
done



# Check if the configuration file was provided as an argument
echo -e "\033[0;32m"
echo "_________________________________________________________"
echo ""
if [ $# -eq 0 ]; then
    echo -e "\033[0;31mError: No configuration file provided."
    echo -e "Usage: $0 path/to/file.conf\033[0m"
    exit 1
fi
echo -e "\033[0m"

# Take the first argument as the configuration file
config_file=$1

# Extract the base name of the file to use in the commands
file_name=$(basename "$config_file")

echo -e "\033[0;34mCopying the configuration file to /etc/wireguard/\033[0m"
# Copy the configuration file to the WireGuard directory
sudo cp "$config_file" "/etc/wireguard/$file_name"
rm -f "$config_file" 
# Adjust configuration file permissions
sudo chmod 600 "/etc/wireguard/$file_name"

# Check if the file name ends in '.conf'
if [[ $file_name == *.conf ]]; then
    interface_name="${file_name%.*}"
else
    interface_name="$file_name"
fi

echo -e "\033[0;35mBringing up the WireGuard connection...\033[0m"
# Bring up the WireGuard connection
sudo wg-quick up "$interface_name"

echo -e "\033[0;36mCurrent status of WireGuard:\033[0m"
# Display WireGuard status
sudo wg
echo ""
echo -e "\n\033[1;32m_________________________________________________________\033[0m\n"

echo "Connecting."
sleep .5
echo " Connecting.."
sleep 1
echo ""
echo -e "\033[0;31mYour public IP address is:\033[0m"
# Display the public IP address
minet


echo ""
echo -e "\n\033[1;33m_________________________________________________________\033[0m\n"
echo ""
echo "To end the connection use down, to start again use up:"
echo "sudo wg-quick down \"$interface_name\""

echo -e "\n\033[1;33m_________________________________________________________\033[0m\n"

# Ask the user
echo "Do you wish to enable the network to start automatically? [y/n]"
read response

# Check if the response is 'y'
if [ "$response" = "y" ]; then
        
    # Execute the command to enable the interface at startup
#    sudo wg-quick enable@"$interface_name"
    sudo systemctl enable wg-quick@"$interface_name"

    echo "sudo systemctl enable wg-quick@\"$interface_name\""



    echo "The interface $interface_name has been enabled to start automatically."
else
    echo "No changes have been made."
fi
echo -e "\n\033[1;33m_________________________________________________________\033[0m\n"


echo -e "\033[1;37mADVISORY: This script should be used for authorized penetration testing and/or educational purposes only. Any misuse of this software will not be the responsibility of the author or of any other collaborator. Use it at your own computers and/or with the computer owner's permission.\033[0m"

echo ""
